// ----------------------------------------------------------------------------
#ifndef CGCoronaGenerator_h
#define CGCoronaGenerator_h 1
// ----------------------------------------------------------------------------
#include "GammaE_Scene.h"
#include "BillBoard/CGBillboardRenderer.h"
#include "CGCorona.h"
// ----------------------------------------------------------------------------
class CGCoronaInstance;
class CGCoronaGenerator : public CGResource
{
	public:

		CGCoronaGenerator() : m_poBBR(NULL), m_poShader(NULL) {};

		/// Initializes the corona generator
		virtual void Init(){};

		/// Creates a corona structure specific to the generator.
		virtual CGCorona* poCreateInstanceData() = 0;

        /// Generates the geometry associated for the given instance
        virtual void UpdateInstance(CGCoronaInstance* _poInst,float _fDeltaT) = 0;

		/// Initializes an independent instance
		virtual void InitInstance(CGCoronaInstance* _poInst) = 0;

		/// Sets the shader for the instances of this corona system generator
		void SetBillboardRenderer(CGBillboardRenderer* _poBBR)
		{
			m_poBBR = _poBBR;
		};

		/// Retrieves the shader used by the instances generated by this corona generator
		virtual CGBillboardRenderer* poGetBillboardRenderer()
		{
			return(m_poBBR);
		};

		/// Sets the shader for the instances of this corona system generator
		void SetShader(CE3D_Shader* _poShader)
		{
			m_poShader = _poShader;
		};

		/// Retrieves the shader used by the instances generated by this corona generator
		virtual CE3D_Shader* poGetShader()
		{
			return(m_poShader);
		};

	protected:

		/*
		The generator classes should implement functions similar to these

		/// Initializes an independent trail
		// virtual void InitTrail(CGCorona*) = 0;

		/// Updates an independent trail
		// virtual void UpdateTrail(CGCorona*) = 0;
		*/

	protected:

		/// The billboard renderer that will store/render the generated geometry
		CGBillboardRenderer* m_poBBR;

		/// The shader used to this corona generator
		CE3D_Shader*		m_poShader;
};
// ----------------------------------------------------------------------------
#endif
// ----------------------------------------------------------------------------
